# Direto no console Terminal Prompt de comandos
# docker run some-mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=123456 -d mysql:8.0.29
#
version: '3'

services:

  db:
    image: db
    command: mysql --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment: 
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: michel
      MYSQL_PASSWORD: 123456

    ports:
      - 3306:3306 
    networks:
      - michel-network


  geekshopping.produtoapi:
    image: ${DOCKER_REGISTRY-}GeekShopping.ProdutoAPI
    build:
      context: .
      dockerfile: GeekShopping.ProdutoAPI/Dockerfile
     
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 44300:80 
    depends_on:
      - db
    networks:
    - michel-network

networks:
  michel-network:
    driver: bridge

